name: "Automated AWS Cloud Deploy"

on:
  push:
    branches:
      - main

jobs:
  terraform-build:
    name: "Run Automation Provisioning"
    runs-on: ubuntu-latest
    steps:
      - name: 1. Download Project Code Files
        uses: actions/checkout@v4

      - name: 2. Load Terraform Tool Engine
        uses: hashicorp/setup-terraform@v3

      - name: 3. Authenticate with AWS Cloud Programmatically
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: 4. Initialize Core Providers
        run: terraform init

      - name: 5. Execute Automated Infrastructure Build
        run: terraform apply -auto-approve

      - name: 6. Automated Status & Password Logger
        run: |
          # Download the official cluster control tool inside the runner
          curl -LO "https://k8s.io(curl -L -s https://k8s.io)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          
          # Fetch the public IP address generated by Terraform
          PUBLIC_IP=$(terraform output -raw your_public_cloud_ip)
          
          echo "=========================================================="
          echo "🚀 YOUR LIVE ARGO CD WEB URL: http://$PUBLIC_IP:30808"
          echo "🚀 YOUR LIVE WEB APP ADDRESS: http://$PUBLIC_IP:30080"
          echo "=========================================================="
          echo "⏳ Waiting 60 seconds for background cloud software installation to finish..."
          sleep 60
